# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5dbc0abdcd283e68585ebe3fda2f039a6d41f7574312b1ed20327e3886c011d61aeb95abf9c783b64aa59ecfce667a4dcda4a036d714974d83790191dd6a5ff

test:
  secret_key_base: bb5d86245542aba5272c9f9dcc2932ebff1a493a499419baa040bef09ec28aff26b3f5873d4a95369e86ebd257b665aab6b62978ad1507c8b8f20a4c972ccabd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
